baseURL = '/'
languageCode = 'ja'
title = '怠惰ローカルブログ'
theme = 'PaperMod'

[params]
  ShowShareButtons = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  assets.favicon = "/favicon.png"

[params.homeInfoParams]
  Title = "ブログ"
  Content = "技術メモ"

[[menu.main]]
  name = "アーカイブ"
  url = "/archives/"
  weight = 10
[[menu.main]]
  name = "検索"
  url = "/search/"
  weight = 20
[[menu.main]]
  name = "タグ"
  url = "/tags/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
